In [2]:
from pycaret.regression import *
import pandas as pd
dataTraining = pd.read_csv('https://raw.githubusercontent.com/davidzarruk/MIAD_ML_NLP_2023/main/datasets/dataTrain_carListings.zip')
regression_setup = setup(data=dataTraining, target='Price')

In [ ]:
best_model = compare_models()

Initiated  . . . . . . . . . . . . . . . . . .               11:17:32
Status     . . . . . . . . . . . . . . . . . .       Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Extra Trees Regressor

Processing:   0%|          | 0/77 [00:00<?, ?it/s]